### PR TITLE
fix: Make the recipe pass validation for new users

### PR DESCRIPTION
**Pull request by gmpinder**

### CODE REVIEW

**Review by fiftydinar — APPROVED** [review]

**Comment by xynydev** [comment]
I think empty configs shouldn't mess up validation; maybe something we can fix in the TypeSpec?

**Comment by gmpinder** [comment]
> I think empty configs shouldn't mess up validation; maybe something we can fix in the TypeSpec?

They would have to support null on the properties that are optional. One of our users ran into that problem

**Comment by xynydev** [comment]
Maybe the issue is only with null arrays being possible parsed as existing non-array values, failing the validation. We could try making optional strings explicitly also support a null or empty string value.

**Comment by xynydev** [comment]
I tested locally; adding an optional array key without defining an error gives an `incorrect type` error. We _could_ allow an empty string in the schemas, but that might break parsing in some cases. A valid alternative, however, would be declaring empty arrays and objects with `key: {}` and `key: []`.

**Pull request merged**
