### PR TITLE
exclude Dolphin .directory files

### PR DESCRIPTION
**Pull request by boredsquirrel**
KDE Dolphin adds these files to every directory for specific configs

### CODE REVIEW

**Comment by fiftydinar** [comment]
I wouldn't add this exclusion.

We won't add any specific exceptions, which would collide with the custom directory structure, which would image-maintainer use.

**Comment by boredsquirrel** [comment]
just read this


> We won't add any specific exceptions, which would collide with the custom directory structure, which would image-maintainer potentially use.

what does this mean?
If I clone this repo and open Dolphin, it will spam every directory with this file. It contains metadata about the icon, settings etc.

I dont know a reason not to include it, as distros using such a named file would collide with KDE Plasma anyways.

Please merge this, currently uBlue is not usable for maintainers on KDE. This is a small change and can be done downstream, but these are hidden files, and the first time having all these .directory files there is annoying

**Comment by gmpinder** [comment]
While we appreciate the PR to solve a problem that you had, we've decided that the only lines that this repo will contain will be related to files that our software generates/uses and shouldn't be committed. Further management of what should be ignored must be handled by users forking this repo. We do not want to take on the responsibility of maintaining a list of all the hidden files that _could_ be there.

**Comment by boredsquirrel** [comment]
fair point.

**Pull request closed without merging**
