### PR TITLE
chore: Move recipe.yml into ./recipes to support proper caching

### PR DESCRIPTION
**Pull request by gmpinder**
Requires https://github.com/blue-build/github-action/pull/39 to be merged and released.

### CODE REVIEW

**Comment by xynydev** [comment]
The recipe in the template shouldn't be moved before modules are changed to support the move.

**Comment by fiftydinar** [comment]
I'm in for this change as it doesn't break anything & it solves the big update sizes that users were complaining about.

Migration from `./config` to `./files` & `./containerfiles` can come later, as it's mostly just a cosmetic improvement in structure.

So, the only question that remains is:
- Should we bump GitHub Action to v1.4.0 now with this fix, or wait for `./config` refactor in bash modules to complete?

**Comment by xynydev** [comment]
I think it would be better to roll out all changes at once, with an announcement post to document it, and the `config/` folder being entirely retired. I wouldn't make an undocumented config the default in the template. We can of course still instruct people to move their recipe file, if they have issues with the update sizes.

**Comment by gmpinder** [comment]
> I think it would be better to roll out all changes at once, with an announcement post to document it, and the `config/` folder being entirely retired. I wouldn't make an undocumented config the default in the template. We can of course still instruct people to move their recipe file, if they have issues with the update sizes.

If that's the case then I don't think we should release the GHA with the cache feature until we have the recipe directory be the default in the template. Releasing a cache focused update to the action without having the default setup make use of it seems counter-intuitive to me. This is something that can be done incrementally and without large sweeping changes that would give immediate benefit to new users.

**Review by fiftydinar — APPROVED** [review]

**Pull request merged**
